### PR TITLE
Project activity feed

### PR DESCRIPTION
**Pull request by martastain**
### Changelog Description

- **Main activity feed**: Stay in the loop with comments, status changes, and assignee updates – all in one place.
- **Filters**: Need to focus? Filter the activity feed by all updates, comments, or checklists.
- **Markdown Support**: Compose clear and well-formatted comments using intuitive markdown syntax.
- **Integrated Checklists**: Organize your workflow and track progress efficiently with built-in checklists.
- **Attachment & Image Previews**: Seamlessly share images and files, with pasting image support for faster workflows.
- **Advanced Mentions**: Improve collaboration with user mentions `@username`, version mentions `@@version`, and task mentions `@@@task`.
- **Comment Cross-posting**: When comments are mentioned or related to other entities within a project, they will automatically show across those entities, promoting better contextual understanding and information flow.
- **Mention Tooltips**: Gain quick context with user mention tooltips.
Compare View: Leverage the new compare view to gain a side-by-side comparison of two different entities.

activity-feed-overview-sh030-compositing

Filters

activity-feed-filters

Markdown Support
activity-feed-markdown

Integrated Checklists
activity-feed-checklists

Attachment & Image Previews
activity-feed-attachments

Advanced Mentions
activity-feed-mentions

Comment Cross-posting
activity-feed-relations

Mention Tooltips
activity-feed-mention-tooltip

### CODE REVIEW

**Comment by mkolar** [comment]
@Innders in the latest experimental, the mentions get wiped out if you edit a comment.

**Comment by antirotor** [comment]
So my first quick notes:
When I want to see the exact time comment is posted, I have no chance. I would expect that it is shown in the tooltip when I hover over the relative time but it gets covered by context menu:
ayon_activity_feed_comment_1

Adding tags looks strange:
image

**Comment by LiborBatek** [comment]
Having hard times to put some web links into post.... as a dumb non coding guy :)

I think also when ```Edit post``` which is already present and putting web links is a bit hard for regular artist :) as there is no the UI with tools for it??

**Comment by antirotor** [comment]
Writing comment - visual feedback on the mode itself. I can't really tell if I am writing in **bold** or not

**Comment by LiborBatek** [comment]
here is what happens if I silly just paste some web page link directly into comment...


https://github.com/ynput/ayon-frontend/assets/112623825/b83a830d-f23e-43f7-8b68-8cf19365f4f2

**Comment by MustafaJafar** [comment]
I thought it's possible to hover over a comment and find a reply button. 

Some Markdown works some doesn't work.
image


I couldn't add a link to video! 
Animation_54

Animation_53

**Comment by MustafaJafar** [comment]
That red box is very confusing. I have no idea what I've done wrong.
Also, My comment is lost :( 
image

**Comment by LiborBatek** [comment]
Im getting the same as @MustafaJafar  when probably ```too long comment``` maybe there should be better ```Error msg``` for such occasion...if too many letters present in the comment.

**Comment by antirotor** [comment]
messing around markdown will at the end strip the information:

putting this in comment:
```
@@[@](@)@@
```
Will end up displaying just `@` in the submitted comment (which is probably fine) - but editing the comment will strip the markdown anyway. So the question is - is to comment stored with markdown or is it somehow processed.

ayon_activity_feed_comment_3

**Comment by antirotor** [comment]
behaving like a little kid, I did a bunch of `.&nbsp;.&nbsp;.&nbsp;.&nbsp;.&nbsp;.&nbsp;.&nbsp;.&nbsp;` resulting in:

ayon_activity_feed_comment_4

probably not a bug, just something to be aware of

**Pull request merged**
