### PR TITLE
fix(Settings): Using default value for new/unset fields

### PR DESCRIPTION
**Pull request by flynput**
@martastain Please confirm that I'm not bloating the form with default values.

https://github.com/user-attachments/assets/6b86a7c2-bdd6-4339-8072-2ce41ffd0dca

### CODE REVIEW

**Review by Innders — APPROVED** [review]
I get these defaults, but someone with better settings knowledge will need to test it.

image

**Comment by iLLiCiTiT** [comment]
Looks like it works for `str` but not for others, like bool and color.

image

**Review by iLLiCiTiT — CHANGES_REQUESTED** [review]
Works for `str`, does not work for bool, color and maybe few more.

**Comment by flynput** [comment]
> Works for `str`, does not work for bool, color and maybe few more.

Just pushed changes that should fix the default value issue for bools/colors/selects fields also.

**Review by iLLiCiTiT — APPROVED** [review]
Works for me

**Review by Innders — APPROVED** [review]

**Pull request merged**
