### PR TITLE
Inbox: New message notification in tab

### PR DESCRIPTION
**Pull request by Innders**
## Description of changes

- WS topic `inbox.message` so all below happens in real time.
- Update Tab title with new `AYON - Unread Message...`
- Update Tab favicon to have little red dot
- User preferences for desktop notifications and notification sounds
- Notification sounds 🔈 
- Desktop notifications (when the AYON tab is focused no sound is played and toast is shown instead)

### Technical details

Also sorted out the favicon to do it properly.

### Additional context

image

(Play with sound)

https://github.com/ynput/ayon-frontend/assets/49156310/644ffbab-eac5-4bd0-ac6d-0f2d5790504c

(When notifications are on but you already have focus on the tab)
image

image

### CODE REVIEW

**Comment by Innders** [comment]
This is a good start and lays the groundwork for real time notifications. Once [Notifications: When a new inbox item is available send to user over WS](https://github.com/ynput/ayon-backend/issues/222) then I can implement:

1. Little chime noise on new message
2. Native desktop notifications
3. Configurable user settings for 1 and 2

**Comment by BigRoy** [comment]
> 2\. Native desktop notifications

This came up by artists here - they'd love having actual notifications going into Windows' notification center (not sure how that works?)

**Comment by Innders** [comment]
> they'd love having actual notifications going into Windows' notification center

This is now added. The easiest way is to click this button on the inbox page and accept the permissions.

image

Otherwise the switch in your profile settings `/account/profile` does the same thing.

**Comment by martastain** [comment]
Desktop notification and sound work fine on Linux / Vivaldi.
I'll update the chime sound this afternoon the volume is quite.... random.

**Review by martastain — APPROVED** [review]

**Pull request merged**
