### PR TITLE
fix(onboarding): Added Linux EL9 disclaimer on platform selection as …

### PR DESCRIPTION
**Pull request by flynput**
Added EL9 Linux platform disclaimer - hard coded for now 

https://github.com/user-attachments/assets/a6b1cd61-634c-4ac7-b859-ff0521224f39

### CODE REVIEW

**Comment by flynput** [comment]
@Innders Please confirm the implementation is as requested.

**Comment by flynput** [comment]
@antirotor Let us know if the implementation is good enough to solve #712 .

**Review by Innders — CHANGES_REQUESTED** [review]
Please remove the icon. Just need a tooltip that appears when hovering the platform card.

**Comment by flynput** [comment]
> Please remove the icon. Just need a tooltip that appears when hovering the platform card.

Updated, screen recording also.

**Comment by antirotor** [comment]
I would say this will do fine. We should provide better compatibility info somewhere in the docs and later on provide link from this page. But so far, this will do.

**Review by Innders — APPROVED** [review]

**Pull request merged**
