### PR TITLE
fix: added chevron and hover effect on StatusSelect

### PR DESCRIPTION
**Pull request by LudoHolbik**
## Changelog Description

Added chevron and hover effect for StatusSelect

image

### CODE REVIEW

**Comment by tokejepsen** [comment]
What is the hover effect?

**Comment by tokejepsen** [comment]
> I suppose it should become slightly brighter as you hover it to indicate you can click it.

@BigRoy sorry I cant visualize frontend code :) Was expecting a gif or video to show the changes.

**Comment by Innders** [comment]
This would be a great time to introduce @LudoHolbik who will be helping us out on the frontend.

Here's a video, the lightness is subtle but I think the arrow is what helps the most. 

(@LudoHolbik asked if he should include a GIF and I said "nah, no one cares" :grimacing: so that's my bad)


https://github.com/ynput/ayon-frontend/assets/49156310/5932fb5b-df2c-4f28-b1b1-85fbedb2feb0

**Review by Innders — APPROVED** [review]

**Comment by BigRoy** [comment]
> and I said "nah, no one cares" 😬 so that's my bad)

And this is the moment @LudoHolbik already learned that we _always care_.

**Pull request merged**
