### PR TITLE
Actions: Browser launcher actions

### PR DESCRIPTION
**Pull request by martastain**
Frontend counterpart to https://github.com/ynput/ayon-backend/pull/183/

https://github.com/ynput/ayon-frontend/assets/49156310/b824b857-c6d1-437e-9c63-6bfc551d5eb3

### CODE REVIEW

**Review by iLLiCiTiT — APPROVED** [review]
Works

**Comment by tanh609** [comment]
Hello, 

I'm using AYON core 0.4.4 and launcher 1.1.0

I've also updated my AYON docker instance. 

However, I still don't see any action. Please advise. 

image

**Comment by iLLiCiTiT** [comment]
Becuase there is no addon adding them yet. For applications actions you need applications addon that have implemneted them, but that is not yet released.

**Comment by tanh609** [comment]
@iLLiCiTiT This look like a very cool feature.

The default AYON launcher is missing thumbnails and it a bit tough to navigate when you have a lot of assets. The browser launcher action is going to be great.

**Pull request merged**
