### PR TITLE
Enhancement: Navigate to browser page on Dashboard task card double click

### PR DESCRIPTION
**Pull request by flynput**
Handling double click event on Kanban tasks, navigating to browser page for said task.
#closes 600

### CODE REVIEW

**Comment by martastain** [comment]
Hooray. This is something my muscle memory is 100% prepared for. Every single time I try to double-click a kanban item :)

**Comment by BigRoy** [comment]
Oh yes baby! 🚀

**Review by Innders — CHANGES_REQUESTED** [review]
Works amazing!!!

I just forgot about the list view. Could add it to `src/pages/UserDashboardPage/UserDashboardTasks/ListGroup/ListGroup.jsx`.

image

**Review by Innders — APPROVED** [review]
Works great, nice one 🎉

**Pull request merged**
