### PR TITLE
Browser: Unify entity details panel

### PR DESCRIPTION
**Pull request by Innders**
## PR Checklist

-   [x] This comment contains a description of changes
-   [x] Referenced issue is linked

## Description of changes

- Replaces the old browser details panel with the new one use on dashboard.
- You can now use the activity feed with folders.
- New Representations tab for versions.

image

https://github.com/ynput/ayon-frontend/assets/49156310/0eea987f-bf9e-4b69-a1dd-b0c08a89aee6

### Technical details

Removes a lot of duplicate code and unifies a details panel for entities into one component and design.

### Testing

1. Open a project
2. Select any entity, (folder, task, version).
3. Click around in the details panel.

1. Select a version
2. Select "representations" tab
3. Select a representation from the table
4. The slide out should appear.

### CODE REVIEW

**Comment by martastain** [comment]
It looks awesome. Trying to tag a version from a version using `@@` does not offer me anything tho. is that expected? shouldn't it offer other versions from the same product?

**Comment by martastain** [comment]
Adding myself as an assignee from the browser does not invalidate kanban view, so in order to see the task there, a page reload is necessary

**Comment by martastain** [comment]
I've created a comment on a task. In the database, relations to all linked versions were created:

image

but I cannot see the task comment in the version feed. Could you please confirm whether there's something wrong in the frontend or graphql resolver? (all activities button is selected).

Interestingly enough, if I do the opposite (create a comment on a version) I can see that comment in the linked task.

**Comment by Innders** [comment]
> but I cannot see the task comment in the version feed

This is the correct behaviour, I don't see merit in seeing comments on a parent task unless it specifically mentions the version.

The version feed should be kept clean for more feedback and review.

The resolvers works, I'm filtering out the comments FE.

**Comment by LudoHolbik** [comment]
Apart from issues reported in activity feed, here is another one:

5. Dropdown not fully visible.

https://github.com/ynput/ayon-frontend/assets/16327908/ee642232-26c1-4824-b5b9-0d89dc18e4c7

**Comment by LudoHolbik** [comment]
6. Not sure if bug or intended but I cant add user/version/task when editing message in version but I can add it in new comment.


https://github.com/ynput/ayon-frontend/assets/16327908/afb12063-0069-4901-97ab-d72902da64dc

**Comment by LudoHolbik** [comment]
And sorry for spamming with issues, its minor stuff, it generally looks and works nicely. 👍👌

**Review by martastain — APPROVED** [review]

**Review by LudoHolbik — APPROVED** [review]

**Comment by Innders** [comment]
Thanks for the reports

5. This would be really tricky to fix and probably not worth it, I suggest you scroll down a bit ;)
6. fixed

**Pull request merged**
