### PR TITLE
708 editor enum dropdown fixes and enhancements remade

### LINKED ISSUE #708: Editor: Enum dropdown fixes and enhancements
Handling string attributes with enumerator has flaws as it is not used much. Here's a list of issues and possible enhancements, that should also cover implementation of https://github.com/ynput/ayon-backend/issues/313

- [ ] In the table, the value is shown instead of the label:

image

- [ ] Label for inherited value is not shown at all:

image

- [ ] "Clear to no value" does not make sense as the value always need to be one of the enum list or null. Currently it tries to set empty list (the same logic as for `list_of_string` attributes), which cause errors. IMO we could remove this button for single value dropdown completely.

image

Additional `color` and `icon` can be used with https://github.com/ynput/ayon-backend/pull/314 In that case, dropdowns could be rendered similarly to status dropdowns.

- [ ] Create an enhanced dropdown that supports icons and colored backgrounds.

Custom dropdown examples:
InstallerSelector: https://github.com/ynput/ayon-frontend/blob/2e6e030e67474ec3fe8a5b6477bf45aed5f33172/src/pages/SettingsPage/Bundles/InstallerSelector.jsx
VariantSelect: https://github.com/ynput/ayon-frontend/blob/b678ff3fd9dc4715f415e6a90be08bdc12c1f776/src/containers/AddonSettings/VariantSelector.jsx
StatusSelect: https://github.com/ynput/ayon-frontend/blob/f24b1a52ce5cab800942d2be2f8ced078021fe15/src/components/status/statusSelect.jsx

### PR DESCRIPTION
**Pull request by flynput**
Several changes were implemented to improve the editor user experience:
- Listing tools column uses custom formatter to display inherited values / No values
- Removed clear buttons on all Dropdown form items for consistency
- Added new option for non-custom Dropdown fields which resets value to 'inherited' when selected

https://github.com/user-attachments/assets/de261059-391b-4d87-898d-4167b3849300

Closes #708

### CODE REVIEW

**Comment by flynput** [comment]
> I'm a bit confused with the dropdown listing `a` for test, and when set... the column in editor displaying `aa`? :)

True, it should use the label instead 👍

**Comment by flynput** [comment]
@BigRoy Fixed the value/label issue, attaching a new screen recording:

https://github.com/user-attachments/assets/f037d4b3-337d-42d5-9849-24b8246162b7

**Comment by BigRoy** [comment]
Nice @flynput - it's a bit unclear but is now in both displaying the **label** or the **value**? Not sure which `a` was of two.

**Comment by flynput** [comment]
> Nice @flynput - it's a bit unclear but is now in both displaying the **label** or the **value**? Not sure which `a` was of two.
> 
> If it's the **label**, then this looks good to me.

Certain attributes have custom formatting - i.e. the Tools one - the rest were displaying by default the value.
That changed to displaying the label if it's an enum & has labels, both in the listing and the form

**Review by BigRoy — APPROVED** [review]
Didn't test but videos look good to me. :)

**Review by Innders — APPROVED** [review]

**Pull request merged**
